#cloud-config
package_update: true
packages:
  - docker.io
  - git
runcmd:
  - systemctl enable docker
  - systemctl start docker
  - mkdir -p /usr/local/lib/docker/cli-plugins
  - curl -SL https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
  - chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  - git clone https://github.com/dmytrosydor/open-data-ai-analytics /app
  - cd /app && docker compose up -d
